name: terraform workflow
on:
  push:
    branches:
      - main
      - develop
permissions: write-all
jobs:
  terraformworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
